var posts = [
  {
    id: "1",
    imgPath: "./background_images/pre/ball.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/ball_4k.png",
  },
  {
    id: "2",
    imgPath: "./background_images/pre/block_day.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/block_day_4k.png",
  },
  {
    id: "3",
    imgPath: "./background_images/pre/block_night.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/block_night_4k.png",
  },
  {
    id: "4",
    imgPath: "./background_images/pre/cliff.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/cliff_4k.png",
  },
  {
    id: "5",
    imgPath: "./background_images/pre/cliff_day.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/cliff_day_4k.png",
  },
  {
    id: "6",
    imgPath: "./background_images/pre/cliff_mid.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/cliff_mid_4k.png",
  },
  {
    id: "7",
    imgPath: "./background_images/pre/cliff_night.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/cliff_night_4k.png",
  },
  {
    id: "8",
    imgPath: "./background_images/pre/color_ball.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/color_ball_4k.png",
  },
  {
    id: "9",
    imgPath: "./background_images/pre/grass_pre.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/grass_pre_4k.png",
  },
  {
    id: "10",
    imgPath: "./background_images/pre/light_ball.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/light_ball_4k.png",
  },
  {
    id: "11",
    imgPath: "./background_images/pre/light_ball_day_pre.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/light_ball_day_pre_4k.png",
  },
  {
    id: "12",
    imgPath: "./background_images/pre/light_ball_mid_pre.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/light_ball_mid_pre_4k.png",
  },
  {
    id: "13",
    imgPath: "./background_images/pre/light_ball_night_pre.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/light_ball_night_pre_4k.png",
  },
  {
    id: "14",
    imgPath: "./background_images/pre/little_pond_(1).png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/little_pond_(1)_4k.png",
  },
  {
    id: "15",
    imgPath: "./background_images/pre/little_pond_(2).png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/little_pond_(2)_4k.png",
  },
  {
    id: "16",
    imgPath: "./background_images/pre/little_pond_(3).png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/little_pond_(3)_4k.png",
  },
  {
    id: "17",
    imgPath: "./background_images/pre/little_pond_v2_cube.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/little_pond_v2_cube_4k.png",
  },
  {
    id: "18",
    imgPath: "./background_images/pre/m_ball.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/m_ball_4k.png",
  },
  {
    id: "19",
    imgPath: "./background_images/pre/puddleday.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/puddleday_4k.png",
  },
  {
    id: "20",
    imgPath: "./background_images/pre/puddlenight.png",
    reg_date: "2020-11-05 18:10:18",
    imgPath4k: "./background_images/images/puddlenight_4k.png",
  },
  {
    id: "21",
    imgPath: "./background_images/pre/rock.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/rock_4k.png",
  },
  {
    id: "22",
    imgPath: "./background_images/pre/rockwithrocks.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/rockwithrocks_4k.png",
  },
  {
    id: "23",
    imgPath: "./background_images/pre/room.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/room_4k.png",
  },
  {
    id: "24",
    imgPath: "./background_images/pre/wall_day.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/wall_day_4k.png",
  },
  {
    id: "25",
    imgPath: "./background_images/pre/wall_day_adj.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/wall_day_adj_4k.png",
  },
  {
    id: "26",
    imgPath: "./background_images/pre/wall_dusk_adj.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/wall_dusk_adj_4k.png",
  },
  {
    id: "27",
    imgPath: "./background_images/pre/wall_mid.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/wall_mid_4k.png",
  },
  {
    id: "28",
    imgPath: "./background_images/pre/wall_mid_adj.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/wall_mid_adj_4k.png",
  },
  {
    id: "29",
    imgPath: "./background_images/pre/wall_night.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/wall_night_4k.png",
  },
  {
    id: "30",
    imgPath: "./background_images/pre/wall_night_adj.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/wall_night_adj_4k.png",
  },
  {
    id: "31",
    imgPath: "./background_images/pre/water_block_adj.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/water_block_adj_4k.png",
  },
  {
    id: "32",
    imgPath: "./background_images/pre/water_block_day.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/water_block_day_4k.png",
  },
  {
    id: "33",
    imgPath: "./background_images/pre/water_block_night.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/water_block_night_4k.png",
  },
  {
    id: "34",
    imgPath: "./background_images/pre/water_block_night_adj.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/water_block_night_adj_4k.png",
  },
  {
    id: "35",
    imgPath: "./background_images/pre/window.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/window_4k.png",
  },
  {
    id: "36",
    imgPath: "./background_images/pre/window_bronze.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/window_bronze_4k.png",
  },
  {
    id: "37",
    imgPath: "./background_images/pre/window_gold.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/window_gold_4k.png",
  },
  {
    id: "38",
    imgPath: "./background_images/pre/window_nickel.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/window_nickel_4k.png",
  },
  {
    id: "39",
    imgPath: "./background_images/pre/window_silver.png",
    reg_date: "2020-11-05 18:10:19",
    imgPath4k: "./background_images/images/window_silver_4k.png",
  },
];
export default posts;
